# Generated by Django 5.0.7 on 2024-08-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_game_rating_remove_game_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='igdb_id',
            field=models.IntegerField(default=-1),
        ),
    ]
