# Generated by Django 5.0.7 on 2024-08-15 12:57

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_game_igdb_id'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='game',
            managers=[
                ('games', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='game',
            name='igdb_id',
            field=models.IntegerField(unique=True),
        ),
    ]
