# Generated by Django 5.0.7 on 2024-08-17 19:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_game_managers_alter_game_igdb_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergamelibrary',
            name='rating',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
        migrations.AlterField(
            model_name='usergamelibrary',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
