# Generated by Django 5.0.7 on 2024-08-24 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_game_id_alter_game_igdb_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='igdb_id',
            new_name='id',
        ),
    ]
