# Generated by Django 5.0.7 on 2024-08-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_igdb_id_game_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='relevance',
            field=models.IntegerField(default=0),
        ),
    ]
