# Generated by Django 5.0.7 on 2024-09-01 17:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_game_image_id_game_relevance'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergamelibrary',
            name='hours_played',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='usergamelibrary',
            name='num_completions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usergamelibrary',
            name='status_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usergamelibrary',
            name='status_playing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usergamelibrary',
            name='status_retired',
            field=models.BooleanField(default=False),
        ),
    ]
