# Generated by Django 5.0.7 on 2024-09-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_usergamelibrary_num_completions'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='steam_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
